//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdMaster { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public int IdService { get; set; }
        public int IdProduct { get; set; }
        public decimal Sum { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Master Master { get; set; }
        public virtual Product Product { get; set; }
        public virtual Service Service { get; set; }
    }
}
